sonar.projectKey=bradtech-oss_stack
sonar.organization=bradtech-oss
sonar.projectName=bradtech-oss-stack
sonar.projectVersion=0.1.0

sonar.sources=packages,apps,infra/tools
sonar.tests=packages,apps
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.astro/**

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
