-- Seed data for Vendors and Unified Devices with autogenerated UUID primary keys and clean dimensions Map
INSERT INTO vendors (id, name, sku, url, details) VALUES
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'Brad Technology', 'BRAD-HQ', 'https://brad.technology', '{"country": "FR", "supportEmail": "support@brad.technology"}'::jsonb),
  ('b1ffcd88-8d0a-3ef7-aa5c-5aa8ac270a22', 'EcoApparel & IoT Sensors', 'ECO-SENSORS', 'https://ecomills.example.com', '{"country": "DE", "supportEmail": "iot@ecomills.example.com"}'::jsonb),
  ('c2aabe77-7e0f-2ef6-994b-4aa7ab160a33', 'Harvest Tech Ltd', 'HARVEST-UK', 'https://harvest-tech.example.com', '{"country": "UK", "supportEmail": "contact@harvest-tech.example.com"}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO devices (id, name, sku, archetype_id, lifecycle_state, dimensions, vendor_info) VALUES
  (
    'd311aa66-6f0e-1ef5-883a-3aa6ba050a44',
    'Soil Moisture Probe V2',
    'BRAD-PROBE-V2-HYBRID',
    'hardware.probe',
    'ASSOCIATED',
    '{"unitSystem": "metric", "height": 450, "width": 65, "depth": 65, "weight": 480, "enclosureRating": "IP68"}'::jsonb,
    '{"vendorUri": "vendors/a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11", "vendorSku": "BRAD-PHY-PCB-HYBRID-01", "status": "ACTIVE", "releaseDate": "2025-06-01", "eolDate": "2030-12-31"}'::jsonb
  ),
  (
    'e422bb55-5f0d-0ef4-7729-2aa5ab040a55',
    'LoRaWAN Outdoor Gateway 868MHz',
    'BRAD-GW-868-OUTDOOR',
    'hardware.gateway',
    'AVAILABLE',
    '{"unitSystem": "metric", "height": 220, "width": 180, "depth": 90, "weight": 1250, "enclosureRating": "IP67"}'::jsonb,
    '{"vendorUri": "vendors/a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11", "vendorSku": "BRAD-GW-MOD-868", "status": "ACTIVE", "releaseDate": "2024-03-15", "eolDate": "2029-12-31"}'::jsonb
  ),
  (
    'f533cc44-4f0c-9ef3-6618-1aa4ab030a66',
    'Agri Weather Station Pro',
    'ECO-WX-STATION-PRO',
    'hardware.weather_station',
    'AVAILABLE',
    '{"unitSystem": "metric", "height": 850, "width": 320, "depth": 320, "weight": 3400, "enclosureRating": "IP66"}'::jsonb,
    '{"vendorUri": "vendors/b1ffcd88-8d0a-3ef7-aa5c-5aa8ac270a22", "vendorSku": "ECO-WX-2026-X", "status": "ACTIVE", "releaseDate": "2025-01-10", "eolDate": "2031-01-01"}'::jsonb
  )
ON CONFLICT (id) DO NOTHING;
