/**
 * Static JSON Catalog & Embedded TypeScript Data Compiler for @bradtech/ontologies.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { loadOntologyCatalog, scanMarkdownFiles } from './loader'
import { parseOkfDocument } from './parser'
import { readFileSync } from 'node:fs'
import { toOpenDataJsonLd } from './extractor'

function build() {
   const dataDir = resolve(__dirname, '../data')
   const distDir = resolve(__dirname, '../dist')
   const srcDir = resolve(__dirname, '../src')

   console.log('Compiling OKF Agricultural Ontologies...')

   const files = scanMarkdownFiles(dataDir)
   const allItems = []

   for (const file of files) {
      const content = readFileSync(file, 'utf-8')
      try {
         const doc = parseOkfDocument(content)
         allItems.push(doc)
      } catch (err) {
         // Skip non-concept files
      }
   }

   const catalog = loadOntologyCatalog(dataDir)

   mkdirSync(distDir, { recursive: true })

   // 1. Write src/embeddedData.ts
   const embeddedTsContent = `/**
 * Auto-generated by build.ts. Do not edit manually.
 */
import type { AnyOntologyItem } from './types'

export const EMBEDDED_ONTOLOGY_ITEMS: AnyOntologyItem[] = ${JSON.stringify(allItems, null, 2)}
`
   const embeddedPath = resolve(srcDir, 'embeddedData.ts')
   writeFileSync(embeddedPath, embeddedTsContent, 'utf-8')
   console.log(` -> Generated static embedded data at ${embeddedPath}`)

   // 2. Write dist/catalog.json
   const compiledCatalog = {
      version: '0.1.0',
      timestamp: new Date().toISOString(),
      itemCount: catalog.items.length,
      items: catalog.items,
      soils: catalog.byDomain.get('soils') || [],
      irrigations: catalog.byDomain.get('irrigations') || [],
      crops: catalog.byDomain.get('crops') || [],
      cropCovers: catalog.byDomain.get('crop-covers') || [],
   }

   const catalogJsonPath = resolve(distDir, 'catalog.json')
   writeFileSync(catalogJsonPath, JSON.stringify(compiledCatalog, null, 2), 'utf-8')
   console.log(` -> Written compiled catalog (${catalog.items.length} concepts) to ${catalogJsonPath}`)

   // 3. Write dist/opendata.jsonld
   const openDataPath = resolve(distDir, 'opendata.jsonld')
   const openData = toOpenDataJsonLd(catalog)
   writeFileSync(openDataPath, JSON.stringify(openData, null, 2), 'utf-8')
   console.log(` -> Written Open Data JSON-LD to ${openDataPath}`)
}

build()
