/**
 * Auto-generated by build.ts. Do not edit manually.
 */
import type { AnyOntologyItem } from './types'

export const EMBEDDED_ONTOLOGY_ITEMS: AnyOntologyItem[] = [
  {
    "type": "crop",
    "id": "triticum-aestivum",
    "title": "Blé tendre (Triticum aestivum)",
    "description": "Céréale à paille annuelle de la famille des Poacées, base de la meunerie et de la panification.",
    "tags": [
      "crop",
      "cereals",
      "annual",
      "field-crop"
    ],
    "translations": {
      "fr": "Blé tendre",
      "en": "Common Wheat",
      "es": "Trigo blando",
      "it": "Frumento tenero",
      "de": "Weichweizen"
    },
    "standards": {
      "eppo": "TRZAX",
      "agrovoc": "c_7951",
      "telepac_rpg": [
        "BTH",
        "BTP"
      ]
    },
    "bodyMarkdown": "# Blé tendre (Triticum aestivum)\n\nGrande culture céréalière mondiale.",
    "category": "cereals",
    "scientificName": "Triticum aestivum L.",
    "agronomy": {
      "rootDepthMaxCm": 120,
      "kcInitial": 0.3,
      "kcMid": 1.15,
      "kcEnd": 0.25,
      "baseTemperatureGdd": 0,
      "waterRequirementMmAnnual": 450
    }
  },
  {
    "type": "crop",
    "id": "zea-mays",
    "title": "Maïs grain et fourrage (Zea mays)",
    "description": "Plante herbacée annuelle en C4 de la famille des Poacées, à forte productivité de biomasse et forts besoins hydriques estivaux.",
    "tags": [
      "crop",
      "cereals",
      "annual",
      "c4",
      "summer-crop"
    ],
    "translations": {
      "fr": "Maïs",
      "en": "Maize / Corn",
      "es": "Maíz",
      "it": "Mais",
      "de": "Mais"
    },
    "standards": {
      "eppo": "ZEAMX",
      "agrovoc": "c_8504",
      "telepac_rpg": [
        "MIS",
        "MID"
      ]
    },
    "bodyMarkdown": "# Maïs (Zea mays)\n\nCulture estivale à haute efficience photosynthétique (C4).",
    "category": "cereals",
    "scientificName": "Zea mays L.",
    "agronomy": {
      "rootDepthMaxCm": 140,
      "kcInitial": 0.35,
      "kcMid": 1.2,
      "kcEnd": 0.5,
      "baseTemperatureGdd": 6,
      "waterRequirementMmAnnual": 600
    }
  },
  {
    "type": "domain",
    "id": "crops",
    "title": "Productions Végétales et Espèces Cultivées",
    "description": "Référentiel international des espèces et cultures indexé sur les codes EPPO, FAO AGROVOC et le Registre Parcellaire Graphique (RPG TéléPAC).",
    "tags": [
      "domain",
      "crop",
      "plant",
      "eppo",
      "agrovoc",
      "telepac"
    ],
    "translations": {
      "fr": "Productions Végétales et Espèces Cultivées",
      "en": "Crops & Cultivated Plant Species",
      "es": "Cultivos y Especies Vegetales"
    },
    "standards": {},
    "bodyMarkdown": "# Productions Végétales et Espèces Cultivées\n\nCe domaine normalise les espèces agricoles avec leurs constantes agronomiques ($K_c$, seuils $GDD$, profondeur racinaire) et leurs correspondances opposables Open Data.\n\n## Espèces Référencées\n- [Vigne cultivée (Vitis vinifera)](vitis-vinifera.md)\n- [Lavande vraie / Lavandin (Lavandula angustifolia)](lavandula-angustifolia.md)\n- [Pommier cultivé (Malus domestica)](malus-domestica.md)\n- [Pêcher / Nectarinier (Prunus persica)](prunus-persica.md)\n- [Blé tendre (Triticum aestivum)](triticum-aestivum.md)\n- [Maïs grain et ensilage (Zea mays)](zea-mays.md)"
  },
  {
    "type": "crop",
    "id": "malus-domestica",
    "title": "Pommier cultivé (Malus domestica)",
    "description": "Arbre fruitier de la famille des Rosacées cultivé pour la production de pommes de table et de transformation.",
    "tags": [
      "crop",
      "arboriculture",
      "fruit",
      "orchard",
      "deciduous"
    ],
    "translations": {
      "fr": "Pommier",
      "en": "Apple Tree",
      "es": "Manzano",
      "it": "Melo",
      "de": "Kulturapfel"
    },
    "standards": {
      "eppo": "MABDO",
      "agrovoc": "c_594",
      "telepac_rpg": [
        "VRG",
        "FPP"
      ]
    },
    "bodyMarkdown": "# Pommier cultivé (Malus domestica)\n\nEspèce majeure de l'arboriculture fruitière tempérée.",
    "category": "arboriculture",
    "scientificName": "Malus domestica Borkh.",
    "agronomy": {
      "rootDepthMaxCm": 180,
      "kcInitial": 0.4,
      "kcMid": 0.95,
      "kcEnd": 0.65,
      "baseTemperatureGdd": 4.5,
      "waterRequirementMmAnnual": 700
    }
  },
  {
    "type": "crop",
    "id": "prunus-persica",
    "title": "Pêcher / Nectarinier (Prunus persica)",
    "description": "Arbre fruitier cultivé pour ses pêches, nectarines et brugnons, sensible aux gelées printanières précoces.",
    "tags": [
      "crop",
      "arboriculture",
      "fruit",
      "orchard",
      "frost-sensitive"
    ],
    "translations": {
      "fr": "Pêcher / Nectarinier",
      "en": "Peach / Nectarine Tree",
      "es": "Melocotonero / Nectarino",
      "it": "Pesco",
      "de": "Pfirsichbaum"
    },
    "standards": {
      "eppo": "PRNPS",
      "agrovoc": "c_6267",
      "telepac_rpg": [
        "VRG",
        "FPN"
      ]
    },
    "bodyMarkdown": "# Pêcher / Nectarinier (Prunus persica)\n\nArbre fruitier méditerranéen et tempéré chaud.",
    "category": "arboriculture",
    "scientificName": "Prunus persica (L.) Batsch",
    "agronomy": {
      "rootDepthMaxCm": 160,
      "kcInitial": 0.45,
      "kcMid": 0.9,
      "kcEnd": 0.6,
      "baseTemperatureGdd": 7,
      "waterRequirementMmAnnual": 650
    }
  },
  {
    "type": "crop",
    "id": "vitis-vinifera",
    "title": "Vigne cultivée (Vitis vinifera)",
    "description": "Liane ligneuse pérenne cultivée pour le raisin de cuve et le raisin de table.",
    "tags": [
      "crop",
      "viticulture",
      "perennial",
      "fruit",
      "wine"
    ],
    "translations": {
      "fr": "Vigne cultivée",
      "en": "Common Grapevine",
      "es": "Vid común",
      "it": "Vite comune",
      "de": "Echte Weinrebe"
    },
    "standards": {
      "eppo": "VITVI",
      "agrovoc": "c_8340",
      "telepac_rpg": [
        "VRC",
        "VRT"
      ]
    },
    "bodyMarkdown": "# Vigne cultivée (Vitis vinifera)\n\nCulture pérenne à enracinement profond, adaptée aux terroirs méditerranéens et tempérés.",
    "category": "viticulture",
    "scientificName": "Vitis vinifera L.",
    "agronomy": {
      "rootDepthMaxCm": 250,
      "kcInitial": 0.3,
      "kcMid": 0.7,
      "kcEnd": 0.45,
      "baseTemperatureGdd": 10,
      "waterRequirementMmAnnual": 450
    }
  },
  {
    "type": "crop",
    "id": "lavandula-angustifolia",
    "title": "Lavande vraie / Lavandin (Lavandula)",
    "description": "Arbrisseau dicotylédone pérenne de la famille des Lamiacées cultivé pour son huile essentielle et ses fleurs.",
    "tags": [
      "crop",
      "aromatics",
      "medicinal",
      "perennial",
      "drought-resistant"
    ],
    "translations": {
      "fr": "Lavande / Lavandin",
      "en": "English Lavender / Lavandin",
      "es": "Lavanda / Espliego",
      "it": "Lavanda vera",
      "de": "Echter Lavendel"
    },
    "standards": {
      "eppo": "LAVAN",
      "agrovoc": "c_4219",
      "telepac_rpg": [
        "PPM",
        "PAR"
      ]
    },
    "bodyMarkdown": "# Lavande / Lavandin (Lavandula angustifolia)\n\nPlante méditerranéenne très rustique, tolérante à la sécheresse estivale et aux sols calcaires filtrants.",
    "category": "aromatics",
    "scientificName": "Lavandula angustifolia Mill.",
    "agronomy": {
      "rootDepthMaxCm": 150,
      "kcInitial": 0.25,
      "kcMid": 0.55,
      "kcEnd": 0.35,
      "baseTemperatureGdd": 7,
      "waterRequirementMmAnnual": 350
    }
  },
  {
    "type": "irrigation",
    "id": "gravity",
    "title": "Gravitaire (Submersion / Planches / Raies)",
    "description": "Irrigation par écoulement de surface guidé par la gravité le long de calants, planches ou sillons.",
    "tags": [
      "irrigation",
      "surface",
      "gravity",
      "traditional"
    ],
    "translations": {
      "fr": "Gravitaire",
      "en": "Surface / Gravity",
      "es": "Gravedad",
      "it": "Irrigazione a scorrimento",
      "de": "Furchen- / Einstau-Bewässerung"
    },
    "standards": {
      "icid": "SURFACE",
      "agrovoc": "c_7531"
    },
    "bodyMarkdown": "# Irrigation Gravitaire (Surface Irrigation)\n\nMéthode ancestrale par ruissellement et submersion contrôlée.",
    "engineering": {
      "method": "surface_gravity",
      "applicationEfficiency": 0.6,
      "wettingPatternFraction": 0.85
    }
  },
  {
    "type": "irrigation",
    "id": "drip",
    "title": "Goutte à goutte (Micro-irrigation)",
    "description": "Système de micro-irrigation localisé en surface ou enterré délivrant l'eau directement au pied des cultures avec une haute efficience.",
    "tags": [
      "irrigation",
      "microirrigation",
      "drip",
      "precision"
    ],
    "translations": {
      "fr": "Goutte à goutte",
      "en": "Drip irrigation",
      "es": "Goteo",
      "it": "Irrigazione a goccia",
      "de": "Tröpfchenbewässerung"
    },
    "standards": {
      "icid": "DRIP",
      "agrovoc": "c_2374"
    },
    "bodyMarkdown": "# Goutte à goutte (Drip Irrigation)\n\nSystème apportant l'eau à faible débit et sous basse pression directement au bulbe racinaire.",
    "engineering": {
      "method": "localized_drip",
      "applicationEfficiency": 0.92,
      "wettingPatternFraction": 0.35
    }
  },
  {
    "type": "irrigation",
    "id": "sprinkler",
    "title": "Aspersion (Pivots / Enrouleurs / Couverture)",
    "description": "Distribution de l'eau sous forme de pluie artificielle sous pression par asperseurs, canons ou rampes mobiles.",
    "tags": [
      "irrigation",
      "sprinkler",
      "overhead"
    ],
    "translations": {
      "fr": "Aspersion",
      "en": "Sprinkler",
      "es": "Aspersión",
      "it": "Irrigazione a pioggia",
      "de": "Beregnung"
    },
    "standards": {
      "icid": "SPRINKLER",
      "agrovoc": "c_7342"
    },
    "bodyMarkdown": "# Irrigation par Aspersion (Sprinkler Irrigation)\n\nSystème simulant une pluie aérienne sous pression.",
    "engineering": {
      "method": "pressurized_sprinkler",
      "applicationEfficiency": 0.78,
      "wettingPatternFraction": 1
    }
  },
  {
    "type": "domain",
    "id": "irrigations",
    "title": "Systèmes et Pratiques d'Irrigation",
    "description": "Méthodes d'apport hydrique agricole classifiées selon les standards internationaux ICID et FAO.",
    "tags": [
      "domain",
      "irrigation",
      "water",
      "icid"
    ],
    "translations": {
      "fr": "Systèmes et Pratiques d'Irrigation",
      "en": "Irrigation Systems & Practices",
      "es": "Sistemas y Prácticas de Riego"
    },
    "standards": {},
    "bodyMarkdown": "# Systèmes et Pratiques d'Irrigation\n\nCe domaine normalise les 4 grandes familles d'apports hydriques avec leur efficience d'application et la fraction de sol mouillée.\n\n## Méthodes Référencées\n- [Sans irrigation (Non irrigué / Pluvial)](none.md)\n- [Goutte à goutte (Micro-irrigation)](drip.md)\n- [Gravitaire (Submersion / Planches / Raies)](gravity.md)\n- [Aspersion (Pivots / Enrouleurs / Couverture intégrale)](sprinkler.md)"
  },
  {
    "type": "irrigation",
    "id": "none",
    "title": "Sans irrigation (Non irrigué / Pluvial)",
    "description": "Parcelle conduite en sec, sans équipement d'apport artificiel d'eau. Les augmentations d'humidité du sol correspondent exclusivement à des pluies ou condensations naturelles.",
    "tags": [
      "irrigation",
      "rainfed",
      "dryland"
    ],
    "translations": {
      "fr": "Sans irrigation (Non irrigué)",
      "en": "No irrigation (Rainfed)",
      "es": "Sin riego (Secano)",
      "it": "Senza irrigazione (In asciutta)",
      "de": "Ohne Bewässerung (Regenfeldbau)"
    },
    "standards": {
      "icid": "RAINFED",
      "agrovoc": "c_2393"
    },
    "bodyMarkdown": "# Sans irrigation (Rainfed)\n\nParcelle entièrement dépendante du régime pluviométrique naturel.",
    "engineering": {
      "method": "rainfed",
      "applicationEfficiency": 1,
      "wettingPatternFraction": 1
    }
  },
  {
    "type": "catalog",
    "id": "osfarm-lexicon",
    "title": "OSFARM Open Agricultural Lexicon & Taxonomies",
    "description": "Flat Open Knowledge Format (OKF v0.1) knowledge repository of international agricultural concepts, soils, crops, and irrigation practices.",
    "tags": [
      "catalog",
      "agriculture",
      "open-data",
      "osfarm",
      "brad"
    ],
    "translations": {
      "fr": "Lexique & Taxonomies Agricoles Ouvertes OSFARM",
      "en": "OSFARM Open Agricultural Lexicon & Taxonomies",
      "es": "Léxico y Taxonomías Agrícolas Abiertas OSFARM"
    },
    "standards": {},
    "bodyMarkdown": "# OSFARM Open Agricultural Lexicon & Taxonomies\n\nWelcome to the **OSFARM / Brad Open Agricultural Lexicon**, structured according to the **Open Knowledge Format (OKF v0.1)**.\n\n## Categories Index\n- [Soils & Textures](soils/)\n- [Irrigation Systems & Methods](irrigations/)\n- [Crops & Cultivated Species](crops/)\n- [Crop Covers & Intercropping](crop-covers/)",
    "timestamp": "2026-08-25T20:00:00Z"
  },
  {
    "type": "soil",
    "id": "silty-clay-loam",
    "title": "Sol Limono-Argileux",
    "description": "Sol composé de 27-40% d'argile et > 40% de limons, très riche chimiquement, sensible à la battance.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda"
    ],
    "translations": {
      "fr": "Sol Limono-Argileux",
      "en": "Silty Clay Loam",
      "es": "Suelo Franco Arcillo Limoso",
      "it": "Suolo Franco Argilloso Limoso",
      "de": "Schluffig-toniger Lehmboden"
    },
    "standards": {
      "inrae": "LA",
      "usda": "Silty Clay Loam",
      "wrb": "Cambisol"
    },
    "bodyMarkdown": "# Sol Limono-Argileux (Silty Clay Loam)\n\nSol profond à forte capacité hydrique, typique des plaines alluviales fertiles.",
    "physics": {
      "fieldCapacityPoint": 36,
      "temporaryWiltingPoint": 21,
      "permanentWiltingPoint": 17,
      "bulkDensityKgM3": 1320,
      "clayPercentageApprox": 34,
      "sandPercentageApprox": 15,
      "siltPercentageApprox": 51
    }
  },
  {
    "type": "soil",
    "id": "clay",
    "title": "Sol Argileux",
    "description": "Sol à forte teneur en argile (> 40%), forte capacité de rétention en eau et plasticité élevée.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda",
      "heavy"
    ],
    "translations": {
      "fr": "Sol Argileux",
      "en": "Clay Soil",
      "es": "Suelo Arcilloso",
      "it": "Suolo Argilloso",
      "de": "Tonboden"
    },
    "standards": {
      "inrae": "A",
      "usda": "Clay",
      "wrb": "Vertisol"
    },
    "bodyMarkdown": "# Sol Argileux (Clay)\n\nLe sol argileux présente une réserve utile élevée mais une cinétique de ressuyage lente. Il est sensible au tassement et à l'asphyxie racinaire en période humide.",
    "physics": {
      "fieldCapacityPoint": 40,
      "temporaryWiltingPoint": 24,
      "permanentWiltingPoint": 20,
      "bulkDensityKgM3": 1250,
      "clayPercentageApprox": 45,
      "sandPercentageApprox": 25,
      "siltPercentageApprox": 30
    }
  },
  {
    "type": "soil",
    "id": "clay-loam",
    "title": "Sol Argilo-Limoneux",
    "description": "Sol équilibré à dominante argileuse et limoneuse (27-40% argile, 20-45% sable), excellente rétention en eau.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda",
      "balanced"
    ],
    "translations": {
      "fr": "Sol Argilo-Limoneux",
      "en": "Clay Loam",
      "es": "Suelo Franco Arcilloso",
      "it": "Suolo Franco Argilloso",
      "de": "Toniger Lehmboden"
    },
    "standards": {
      "inrae": "AL",
      "usda": "Clay Loam",
      "wrb": "Luvisol"
    },
    "bodyMarkdown": "# Sol Argilo-Limoneux (Clay Loam)\n\nSol agricole très fertile et polyvalent, offrant une très bonne réserve utile et une bonne porosité structurale.",
    "physics": {
      "fieldCapacityPoint": 35,
      "temporaryWiltingPoint": 20,
      "permanentWiltingPoint": 16,
      "bulkDensityKgM3": 1300,
      "clayPercentageApprox": 32,
      "sandPercentageApprox": 33,
      "siltPercentageApprox": 35
    }
  },
  {
    "type": "soil",
    "id": "sandy-clay",
    "title": "Sol Sablo-Argileux",
    "description": "Sol contenant 35-55% d'argile et 45-65% de sable, combinant plasticité et drainage granulaire.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda"
    ],
    "translations": {
      "fr": "Sol Sablo-Argileux",
      "en": "Sandy Clay",
      "es": "Suelo Arcillo Arenoso",
      "it": "Suolo Argilloso Sabbioso",
      "de": "Sandiger Tonboden"
    },
    "standards": {
      "inrae": "SA",
      "usda": "Sandy Clay",
      "wrb": "Acrisol"
    },
    "bodyMarkdown": "# Sol Sablo-Argileux (Sandy Clay)\n\nTexture combinant argile active et squelette sableux aéré.",
    "physics": {
      "fieldCapacityPoint": 32,
      "temporaryWiltingPoint": 18,
      "permanentWiltingPoint": 14,
      "bulkDensityKgM3": 1400,
      "clayPercentageApprox": 40,
      "sandPercentageApprox": 50,
      "siltPercentageApprox": 10
    }
  },
  {
    "type": "soil",
    "id": "silt",
    "title": "Sol Limoneux Pur",
    "description": "Sol composé de plus de 80% de limon et moins de 12% d'argile, très soyeux, très sensible à la battance et au compactage superficiel.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda"
    ],
    "translations": {
      "fr": "Sol Limoneux Pur",
      "en": "Silt Soil",
      "es": "Suelo Limoso",
      "it": "Suolo Limoso",
      "de": "Schluffboden"
    },
    "standards": {
      "inrae": "LL",
      "usda": "Silt",
      "wrb": "Fluvisol"
    },
    "bodyMarkdown": "# Sol Limoneux Pur (Silt)\n\nSol riche mais exigeant une vigilance sur la structure et le travail du sol.",
    "physics": {
      "fieldCapacityPoint": 31,
      "temporaryWiltingPoint": 15,
      "permanentWiltingPoint": 11,
      "bulkDensityKgM3": 1360,
      "clayPercentageApprox": 8,
      "sandPercentageApprox": 7,
      "siltPercentageApprox": 85
    }
  },
  {
    "type": "soil",
    "id": "sand",
    "title": "Sol Sableux",
    "description": "Sol très filtrant composé de plus de 85% de particules de sable, très faible réserve utile, réchauffement quasi immédiat.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda",
      "draining"
    ],
    "translations": {
      "fr": "Sol Sableux",
      "en": "Sandy Soil",
      "es": "Suelo Arenoso",
      "it": "Suolo Sabbioso",
      "de": "Sandboden"
    },
    "standards": {
      "inrae": "S",
      "usda": "Sand",
      "wrb": "Arenosol"
    },
    "bodyMarkdown": "# Sol Sableux (Sand)\n\nSol très drainant nécessitant des apports d'eau fréquents et fractionnés (goutte à goutte).",
    "physics": {
      "fieldCapacityPoint": 12,
      "temporaryWiltingPoint": 6,
      "permanentWiltingPoint": 4,
      "bulkDensityKgM3": 1550,
      "clayPercentageApprox": 5,
      "sandPercentageApprox": 90,
      "siltPercentageApprox": 5
    }
  },
  {
    "type": "soil",
    "id": "silt-loam",
    "title": "Sol Limono-Sableux / Limon Fin",
    "description": "Sol composé de plus de 50% de limons, doux au toucher, très filtrant et sensible à l'érosion éolienne et hydrique.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda",
      "light"
    ],
    "translations": {
      "fr": "Sol Limono-Sableux / Limon Fin",
      "en": "Silt Loam",
      "es": "Suelo Franco Limoso",
      "it": "Suolo Franco Limoso",
      "de": "Schluffiger Lehmboden"
    },
    "standards": {
      "inrae": "LS",
      "usda": "Silt Loam",
      "wrb": "Luvisol"
    },
    "bodyMarkdown": "# Sol Limono-Sableux (Silt Loam)\n\nSol léger et facile à travailler.",
    "physics": {
      "fieldCapacityPoint": 28,
      "temporaryWiltingPoint": 13,
      "permanentWiltingPoint": 10,
      "bulkDensityKgM3": 1380,
      "clayPercentageApprox": 12,
      "sandPercentageApprox": 28,
      "siltPercentageApprox": 60
    }
  },
  {
    "type": "domain",
    "id": "soils",
    "title": "Sols et Textures Pédologiques",
    "description": "Classification internationale des textures et profils de sol basée sur le triangle textural INRAE/USDA et le référentiel mondial FAO WRB.",
    "tags": [
      "domain",
      "soil",
      "pedology",
      "physics"
    ],
    "translations": {
      "fr": "Sols et Textures Pédologiques",
      "en": "Soils & Pedological Textures",
      "es": "Suelos y Texturas Pedológicas"
    },
    "standards": {},
    "bodyMarkdown": "# Sols et Textures Pédologiques\n\nCe domaine regroupe les 9 classes texturales majeures du sol avec leurs constantes physiques étalonnées pour le calcul des réserves utiles ($RU = HCC - PFP$) et le suivi capacitif.\n\n## Textures Référencées\n- [Argileux (Clay)](clay.md)\n- [Argilo-limoneux (Clay Loam)](clay-loam.md)\n- [Limono-argileux (Silty Clay Loam)](silty-clay-loam.md)\n- [Limoneux (Loam)](loam.md)\n- [Limon fin / Limoneux très fin (Silt Loam)](silt-loam.md)\n- [Sablo-argileux (Sandy Clay)](sandy-clay.md)\n- [Sablo-argilo-limoneux (Sandy Clay Loam)](sandy-clay-loam.md)\n- [Sablo-limoneux (Sandy Loam)](sandy-loam.md)\n- [Sableux (Sand)](sand.md)"
  },
  {
    "type": "soil",
    "id": "sandy-clay-loam",
    "title": "Sol Sablo-Argilo-Limoneux",
    "description": "Sol contenant 20-35% d'argile, 45-80% de sable et moins de 28% de limon, sol d'arboriculture et de vigne très répandu.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda"
    ],
    "translations": {
      "fr": "Sol Sablo-Argilo-Limoneux",
      "en": "Sandy Clay Loam",
      "es": "Suelo Franco Arcillo Arenoso",
      "it": "Suolo Franco Argilloso Sabbioso",
      "de": "Sandig-toniger Lehmboden"
    },
    "standards": {
      "inrae": "SAL",
      "usda": "Sandy Clay Loam",
      "wrb": "Calcisol"
    },
    "bodyMarkdown": "# Sol Sablo-Argilo-Limoneux (Sandy Clay Loam)\n\nSol chaud de printemps, drainant et bien pourvu en réserves.",
    "physics": {
      "fieldCapacityPoint": 29,
      "temporaryWiltingPoint": 15,
      "permanentWiltingPoint": 12,
      "bulkDensityKgM3": 1420,
      "clayPercentageApprox": 27,
      "sandPercentageApprox": 53,
      "siltPercentageApprox": 20
    }
  },
  {
    "type": "soil",
    "id": "loam",
    "title": "Sol Limoneux / Franc",
    "description": "Sol franc idéal réunissant sable (40%), limon (40%) et argile (20%), aéré, drainant et retenant l'eau.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda",
      "fertile"
    ],
    "translations": {
      "fr": "Sol Limoneux / Franc",
      "en": "Loam Soil",
      "es": "Suelo Franco",
      "it": "Suolo Franco",
      "de": "Lehmboden"
    },
    "standards": {
      "inrae": "L",
      "usda": "Loam",
      "wrb": "Phaeozem"
    },
    "bodyMarkdown": "# Sol Limoneux Franc (Loam)\n\nTexture idéale par excellence en agronomie.",
    "physics": {
      "fieldCapacityPoint": 30,
      "temporaryWiltingPoint": 15,
      "permanentWiltingPoint": 12,
      "bulkDensityKgM3": 1350,
      "clayPercentageApprox": 20,
      "sandPercentageApprox": 40,
      "siltPercentageApprox": 40
    }
  },
  {
    "type": "soil",
    "id": "sandy-loam",
    "title": "Sol Sablo-Limoneux",
    "description": "Sol contenant plus de 50% de sable et moins de 20% d'argile, réchauffement très rapide, réserve utile modérée.",
    "tags": [
      "soil",
      "texture",
      "inrae",
      "usda",
      "warm"
    ],
    "translations": {
      "fr": "Sol Sablo-Limoneux",
      "en": "Sandy Loam",
      "es": "Suelo Franco Arenoso",
      "it": "Suolo Franco Sabbioso",
      "de": "Sandiger Lehmboden"
    },
    "standards": {
      "inrae": "SL",
      "usda": "Sandy Loam",
      "wrb": "Arenosol"
    },
    "bodyMarkdown": "# Sol Sablo-Limoneux (Sandy Loam)\n\nSol aéré favorisant l'enracinement rapide des cultures maraîchères et pérennes.",
    "physics": {
      "fieldCapacityPoint": 22,
      "temporaryWiltingPoint": 11,
      "permanentWiltingPoint": 8,
      "bulkDensityKgM3": 1450,
      "clayPercentageApprox": 12,
      "sandPercentageApprox": 68,
      "siltPercentageApprox": 20
    }
  },
  {
    "type": "crop-cover",
    "id": "bare-soil",
    "title": "Sol Nu / Désherbage Mécanique",
    "description": "Sol maintenu sans végétation adventice par travail superficiel ou binage. Zéro compétition hydrique, mais forte exposition à l'érosion et au ruissellement.",
    "tags": [
      "crop-cover",
      "tilled",
      "bare-soil"
    ],
    "translations": {
      "fr": "Sol Nu",
      "en": "Bare Soil",
      "es": "Suelo Desnudo",
      "it": "Suolo Nudo",
      "de": "Offener Boden"
    },
    "standards": {
      "agrovoc": "c_34125"
    },
    "bodyMarkdown": "# Sol Nu (Bare Soil)\n\nModalité sans couvert réduisant la concurrence en eau mais exposant la structure du sol.",
    "effects": {
      "soilProtectionFactor": 0.1,
      "waterCompetitionIndex": 0,
      "nitrogenFixation": false
    }
  },
  {
    "type": "crop-cover",
    "id": "permanent-sod",
    "title": "Enherbement Permanent Maîtrisé",
    "description": "Gazon ou graminées pérennes installées durablement sur l'inter-rang, tondues régulièrement pour limiter la concurrence hydrique.",
    "tags": [
      "crop-cover",
      "permanent",
      "sod",
      "grass"
    ],
    "translations": {
      "fr": "Enherbement Permanent",
      "en": "Permanent Sod Cover",
      "es": "Cubierta Permanente",
      "it": "Inerbimento permanente",
      "de": "Dauerbegrünung"
    },
    "standards": {
      "agrovoc": "c_3313"
    },
    "bodyMarkdown": "# Enherbement Permanent (Permanent Sod)\n\nProtection maximale contre l'érosion et traficabilité par tous les temps.",
    "effects": {
      "soilProtectionFactor": 0.95,
      "waterCompetitionIndex": 0.55,
      "nitrogenFixation": false
    }
  },
  {
    "type": "crop-cover",
    "id": "sown-legume",
    "title": "Couvert Semé de Légumineuses / Engrais Verts",
    "description": "Mélange semé (trèfle, féverole, vesce) apportant un enrichissement en azote symbiotique et une structuration profonde du sol.",
    "tags": [
      "crop-cover",
      "legume",
      "green-manure",
      "nitrogen-fixation"
    ],
    "translations": {
      "fr": "Semis de Légumineuses / Engrais Vert",
      "en": "Sown Legume / Green Manure",
      "es": "Siembra de Leguminosas / Abono Verde",
      "it": "Soffietto di leguminose",
      "de": "Einsaat von Leguminosen"
    },
    "standards": {
      "agrovoc": "c_3364"
    },
    "bodyMarkdown": "# Couvert de Légumineuses (Legume Cover)\n\nApport symbiotique d'azote atmosphérique et restructuration du sol.",
    "effects": {
      "soilProtectionFactor": 0.85,
      "waterCompetitionIndex": 0.3,
      "nitrogenFixation": true
    }
  },
  {
    "type": "domain",
    "id": "crop-covers",
    "title": "Couverts Végétaux et Gestion des Inter-Rangs",
    "description": "Modalités de gestion du sol, enherbement spontané, semis de légumineuses et paillage.",
    "tags": [
      "domain",
      "cover",
      "agroecology",
      "soil-health"
    ],
    "translations": {
      "fr": "Couverts Végétaux et Inter-Rangs",
      "en": "Crop Covers & Inter-Row Management",
      "es": "Cubiertas Vegetales y Manejo de Calles"
    },
    "standards": {},
    "bodyMarkdown": "# Couverts Végétaux et Inter-Rangs\n\nCe domaine qualifie l'état de surface du sol, la protection contre l'érosion et la compétition hydrique inter-rangs.\n\n## Modalités Référencées\n- [Sol Nu / Travail du sol mécanique](bare-soil.md)\n- [Enherbement spontané temporaire](spontaneous-grass.md)\n- [Couverts semés de légumineuses / Engrais verts](sown-legume.md)\n- [Enherbement permanent maîtrisé](permanent-sod.md)"
  },
  {
    "type": "crop-cover",
    "id": "spontaneous-grass",
    "title": "Enherbement Spontané Temporaire",
    "description": "Développement de la flore naturelle locale maîtrisé par fauche ou broyage périodique.",
    "tags": [
      "crop-cover",
      "spontaneous",
      "grass",
      "eco"
    ],
    "translations": {
      "fr": "Enherbement Spontané",
      "en": "Spontaneous Grass Cover",
      "es": "Cubierta Espontánea",
      "it": "Inerbimento spontaneo",
      "de": "Spontanbegrünung"
    },
    "standards": {
      "agrovoc": "c_3313"
    },
    "bodyMarkdown": "# Enherbement Spontané (Spontaneous Grass)\n\nFavorise la portance des engins et la biodiversité sans coût d'implantation.",
    "effects": {
      "soilProtectionFactor": 0.7,
      "waterCompetitionIndex": 0.4,
      "nitrogenFixation": false
    }
  }
]
