apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: bradtech
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bradtech-stack
data:
  POSTGRES_DB: "bradtech_db"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  PGPORT: "5432"
